#!/bin/bash

source /opt/ros/foxy/setup.bash
source ~/colcon_ws/install/setup.bash

sleep 20

# export ROS_HOSTNAME=ros2
# export ROS_MASTER_URI=http://ros2:11311
# export ROS_HOME=~/.ros

ros2 launch roas2_bringup nav2.launch.py
