#!/bin/bash

source /opt/ros/humble/setup.bash
source ~/colcon_ws/install/setup.bash

sleep 25

# export ROS_HOSTNAME=ros2
# export ROS_MASTER_URI=http://ros2:11311
# export ROS_HOME=~/.ros

ros2 launch nav_lv subpub.launch.py
